#undef RGB_MATRIX_DEFAULT_MODE
#undef RGB_DEFAULT_COLOR
#undef DEFAULT_SLEEP_TOGGLE
#undef DEFAULT_USB_SLEEP_TOGGLE
#undef DEFAULT_DEEP_SLEEP_TOGGLE
#undef DEFAULT_SLEEP_TIMEOUT
#undef DEFAULT_CAPS_INDICATOR_TYPE
#undef DEFAULT_BATTERY_INDICATOR_BRIGHTNESS
#undef DEFAULT_LIGHT_CUSTOM_KEYS
#undef DEFAULT_SIDE_MODE
#undef DEFAULT_SIDE_BRIGHTNESS
#undef DEFAULT_SIDE_SPEED
#undef DEFAULT_SIDE_RGB
#undef DEFAULT_SIDE_COLOR
#undef DEFAULT_RIGHT_SIDE_MODE
#undef DEFAULT_RIGHT_SIDE_BRIGHTNESS
#undef DEFAULT_RIGHT_SIDE_SPEED
#undef DEFAULT_RIGHT_SIDE_RGB
#undef DEFAULT_RIGHT_SIDE_COLOR
#undef DEFAULT_DETECT_NUMLOCK
#undef DEFAULT_BATTERY_INDICATOR_NUMERIC
#undef DEFAULT_SHOW_SOCD_INDICATOR


#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_TYPING_HEATMAP
#define RGB_DEFAULT_COLOR 168

#define DEFAULT_SLEEP_TOGGLE true
#define DEFAULT_USB_SLEEP_TOGGLE false
#define DEFAULT_DEEP_SLEEP_TOGGLE true
#define DEFAULT_SLEEP_TIMEOUT 20
#define DEFAULT_CAPS_INDICATOR_TYPE CAPS_INDICATOR_SIDE
#define DEFAULT_BATTERY_INDICATOR_BRIGHTNESS 100
#define DEFAULT_LIGHT_CUSTOM_KEYS 0
#define DEFAULT_SIDE_MODE 0
#define DEFAULT_SIDE_BRIGHTNESS 3
#define DEFAULT_SIDE_SPEED 2
#define DEFAULT_SIDE_RGB 1
#define DEFAULT_SIDE_COLOR 0
#define DEFAULT_RIGHT_SIDE_MODE 0
#define DEFAULT_RIGHT_SIDE_BRIGHTNESS 3
#define DEFAULT_RIGHT_SIDE_SPEED 2
#define DEFAULT_RIGHT_SIDE_RGB 1
#define DEFAULT_RIGHT_SIDE_COLOR 0
#define DEFAULT_DETECT_NUMLOCK 0
#define DEFAULT_BATTERY_INDICATOR_NUMERIC 1
#define DEFAULT_SHOW_SOCD_INDICATOR 1

/* qmk features */
#define FLOW_TAP_TERM 150
#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
